### ISSUE TITLE
Regarding conversion from character level to word level

### ISSUE THREAD

**Issue by jaytimbadia** [santiviquez/harry-potter-rnn#2]
Hey, wonderful work!!

Just one quick question.

Here, we get character level embeddings once we train fully, is there any way we can get word level from it, or need to try another model?

I tried taking character level embeddings for a word and did an average but the results are not satisfactory.
E.g. Harry Potter and Carbon Dioxide are giving 90% cosine similarity.

Any thoughts or any repo can you suggest which learns word embeddings with text generation as a downstream task.
Thank you!!

Asked here since I didn't found any contact details of yours!

**Comment by santiviquez** [comment]
Hi, thanks for reaching out.

To be able to implement word-level embeddings instead of char level you need to make some modifications to the [train_text_generator](https://github.com/santiviquez/harry-potter-rnn/blob/master/model/train_text_generator.py) file. So instead of splitting the data in chars, you'll be splitting it in words. And then encode those words.

I found a couple of interesting post about it that could help you:

- [What is the difference between word-based and char-based text generation RNNs?](https://datascience.stackexchange.com/questions/13138/what-is-the-difference-between-word-based-and-char-based-text-generation-rnns)

- [Understanding Word Embeddings from scratch | LSTM model |
](https://towardsdatascience.com/word-embeddings-and-the-chamber-of-secrets-lstm-gru-tf-keras-de3f5c21bf16)
